export enum DataResource {
  CONTACTS = 'CONTACTS',
  PERSON_CONTACTS = 'PERSON_CONTACTS',
  ORGANIZATION_CONTACTS = 'ORGANIZATION_CONTACTS',
  ASSETS = 'ASSETS',
  CREDENTIALS = 'CREDENTIALS',
  WORKFLOWS = 'WORKFLOWS',
  DOCUMENTS = 'DOCUMENTS',
  IDENTIFIERS = 'key-management/identifiers',
  KEYS = 'KEYS',
  QUERIES = 'QUERIES',
  CREDENTIAL_DESIGNS = 'CREDENTIAL_DESIGNS',
}
