export enum DataResource {
  CONTACTS = 'CONTACTS',
  PERSON_CONTACTS = 'PERSON_CONTACTS',
  ORGANIZATION_CONTACTS = 'ORGANIZATION_CONTACTS',
  ASSETS = 'ASSETS',
  CREDENTIALS = 'CREDENTIALS',
  DOCUMENTS = 'DOCUMENTS',
  IDENTIFIERS = 'key-management/identifiers',
  EXTERNAL_IDENTIFIERS = 'key-management/external-identifiers',
  KEYS = 'KEYS',
  QUERIES = 'QUERIES',
  CREDENTIAL_DESIGNS = 'CREDENTIAL_DESIGNS',
}

export enum BookingDataResource {
  RESOURCES = 'BOOKING_RESOURCES',
  CATEGORIES = 'BOOKING_CATEGORIES',
  POLICIES = 'BOOKING_POLICIES',
  SCHEDULES = 'BOOKING_SCHEDULES',
  REQUIREMENTS = 'BOOKING_REQUIREMENTS',
  BOOKINGS = 'BOOKINGS',
  // New composite schedule and group resources
  GROUPS = 'BOOKING_GROUPS',
  SCHEDULE_SETS = 'BOOKING_SCHEDULE_SETS',
  SCHEDULE_SET_ASSIGNMENTS = 'BOOKING_SCHEDULE_SET_ASSIGNMENTS',
  POLICY_ASSIGNMENTS = 'BOOKING_POLICY_ASSIGNMENTS',
}
