name: sphereon-standalone-agent

services:
  standalone-agent:
    container_name: sphereon-standalone-agent
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IS_WALLET_ENABLED: false
      CONF_PATH: ./conf
#      If you change the conf volume mount point below adjust the above env var as well

    env_file:
      - .env
    tty: true
    build:
      context: ../..
      dockerfile: ./docker/standalone-agent/Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - ../../packages/agent/conf/examples:/opt/agent/packages/agent/conf:ro
      #      If you change the conf volume mount point adjust the above env var as well
      - ./volumes/db:/opt/agent/packages/agent/db:rw
