name: sphereon-standalone-agent

services:
  standalone-agent-full:
    container_name: sphereon-standalone-agent-full
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IS_WALLET_ENABLED: false
    env_file:
      - .env
    tty: true
    build:
      context: ../..
      dockerfile: ./docker/standalone-agent-full/Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - ./volumes/conf:/opt/agent/packages/agent/conf:ro
      - ./volumes/database:/opt/agent/packages/agent/database:rw
