version: '3.8'

services:
  standalone-agent-issuer:
    container_name: sphereon-standalone-agent-issuer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    tty: true
    build:
      context: ../../packages/agent
      dockerfile: ../../docker/standalone-agent-issuer/Dockerfile
    ports:
      - "5001:5001"
